Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [4]:
import numpy as np

In [12]:
n = input("Введите число ")
np.flipud(np.arange(0, int(n)))


Введите число 100


array([99, 98, 97, 96, 95, 94, 93, 92, 91, 90, 89, 88, 87, 86, 85, 84, 83,
       82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66,
       65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49,
       48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [30]:
n = int(input("Введите число "))

diagonal = np.diag(np.flipud(np.arange(0, n)), k=0)
print(diagonal)
print(sum(np.diagonal(diagonal)))
#a = n-1
#diagonal_sum = a * (a + 1) / 2
#print(diagonal_sum)

Введите число 10
[[9 0 0 0 0 0 0 0 0 0]
 [0 8 0 0 0 0 0 0 0 0]
 [0 0 7 0 0 0 0 0 0 0]
 [0 0 0 6 0 0 0 0 0 0]
 [0 0 0 0 5 0 0 0 0 0]
 [0 0 0 0 0 4 0 0 0 0]
 [0 0 0 0 0 0 3 0 0 0]
 [0 0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0]]
45


Задание 3
Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

In [44]:
a = np.array([
    [4, 2, 1],
    [1, 3, 0],
    [0, 5, 4]
])
b = np.array([4, 12, -3])

In [45]:
from numpy import linalg

In [46]:
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [47]:
np.allclose( np.dot(a, linalg.solve(a, b)), b )

True